spring.application.name=stock-webpage

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3308/managing
#spring.datasource.username=system
#spring.datasource.password=0806
spring.datasource.url=jdbc:mariadb://localhost:3306/managingTest
spring.datasource.username=root
spring.datasource.password=0806

server.port=8090

# ======================
# Logging
# ======================
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.com.stock=DEBUG
logging.level.org.mybatis=DEBUG

# ======================
# MyBatis
# ======================
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.stock.webpage.dto
mybatis.configuration.map-underscore-to-camel-case=true