spring.application.name=stock-webpage

server.port=9090

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ======================
# Logging
# ======================
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
# 마이바티스와 비즈니스 로직의 쿼리 로그를 INFO로 올려서 숨김
logging.level.com.stock=INFO
logging.level.org.mybatis=INFO
# API 호출(컨트롤러 매핑 정보)만 터미널에 딱 찍히도록 설정
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.com.stock.webpage.controller=DEBUG

# ======================
# MyBatis
# ======================
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.stock.webpage.dto
mybatis.configuration.map-underscore-to-camel-case=true

# ======================
# Batch CSV File Upload Directory
# ======================
batch.csv.dir=${BATCH_CSV_DIR:/volume1/finstack/workspace/STOCK-DATA-PIPELINE/BATCH_CODE/csvDir}