spring.application.name=stock-webpage

server.port=9090

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://infra-mariadb:3306/managing
spring.datasource.username=system
spring.datasource.password=0806

# ======================
# Logging
# ======================
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.com.stock=DEBUG
logging.level.org.mybatis=DEBUG

# ======================
# MyBatis
# ======================
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.stock.webpage.dto
mybatis.configuration.map-underscore-to-camel-case=true
