name: Build and Push Docker Image (Stock Webpage)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      - name: Build Spring Boot Jar
        run: ./gradlew build -x test


      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/gmdcjdakdcjd/stock-webpage:latest .


      - name: Push Docker Image
        run: |
          docker push ghcr.io/gmdcjdakdcjd/stock-webpage:latest